services:
    php-fpm:
        build:
            context: .
            dockerfile: docker/php-fpm/Dockerfile
        restart: unless-stopped
#        env_file:
#            - .env
        volumes:
            - .:/var/www/project
        depends_on:
            mysql:
                condition: service_healthy
        networks:
            - app-network

    nginx:
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - .:/var/www/project
        depends_on:
            - php-fpm
        networks:
            - app-network

    mysql:
        image: mysql:8.0
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - "127.0.0.1:3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - app-network
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD}" ]
            interval: 5s
            timeout: 5s
            retries: 5

    rabbitmq:
        image: rabbitmq:3.13-management-alpine
        environment:
            - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
            - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
        ports:
            - "5672:5672"
            - "15672:15672"
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq
        networks:
            - app-network

    worker:
        build:
            context: .
            dockerfile: docker/php-fpm/Dockerfile
        volumes:
            - .:/var/www/project
        command: php bin/console messenger:consume async -vv
        depends_on:
            rabbitmq:
                condition: service_started
            mysql:
                condition: service_healthy
        networks:
            - app-network
        restart: always

networks:
    app-network:
        driver: bridge

volumes:
    mysql_data:
    rabbitmq_data:
